language: java
jdk:
  - openjdk11

#os:
#  - linux
#  - osx
#  - windows

jobs:
  include:
    - os: linux
      env: DUMMY=alreadyHasJava
    - os: osx
      env: DUMMY=alreadyHasJava
    - os: windows
      language: shell
      env: JAVA_HOME2="c:\Program Files\Java\jdk1.8.0_221"
install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install jdk8; fi
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install windows-sdk-7.1 kb2519277; fi

before_script:
  - chmod +x gradlew
script:
  - ./gradlew check --info
  - if [ $TRAVIS_OS_NAME  = windows ]; then zip build/graal/checksum.exe build/graal/checksum-$TRAVIS_OS_NAME.zip ; fi
  - if [ $TRAVIS_OS_NAME != windows ]; then zip build/graal/checksum build/graal/checksum-$TRAVIS_OS_NAME.zip ; fi

# Deploy the resulting artifact to GitHub Releases
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: build/graal/checksum-$TRAVIS_OS_NAME.zip
#  skip_cleanup: true
#  on:
#    tags: true

# avoid uploading the cache after every build
#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
