language: java
jdk:
  - openjdk8

os:
  - linux
  - osx
  - windows

#compiler:
#  - gcc
#  - clang

before_install: choco install windows-sdk-7.1 kb2519277


before_script:
  - chmod +x gradlew
script:
  - ./gradlew check --info


# avoid uploading the cache after every build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/