language: java
jdk:
  - openjdk11

os:
  - linux
  - osx
  - windows

jobs:
  include:
    - os: linux
      env: TOXENV=py32
    - os: osx
      language: generic
      env: TOXENV=py32
    - os: windows
      language: generic
      env: TOXENV=py33
install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install windows-sdk-7.1 kb2519277; fi
#  - ./.travis/install.sh


before_script:
  - chmod +x gradlew
script:
  - ./gradlew check --info


# avoid uploading the cache after every build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/