name: Java CI

on: [push]

jobs:
  build-ubuntu-mac:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Rename the artifact to OS-unique name
      shell: bash
      run: |
        value=`cp build/graal/checksum build/graal/checksum-${{ matrix.os }}`
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: checksum-${{ matrix.os }}
        path: build/graal

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: List Chocolatey Installed Packages
        continue-on-error: true
        run: |
          choco list -l
      - name: Print Installed MS VC++ Redistributables
        shell: powershell
        run: Get-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*" | Where {$_.DisplayName -clike 'Microsoft Visual C++ 20* Redistributable*'}
      - name: Uninstall Installed MS VC++ Redistributables
        shell: powershell
        run: |
          $apps = Get-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*" | Where {$_.DisplayName -clike 'Microsoft Visual C++ 20* Redistributable*'}
          foreach ($app in $apps) {$app.Uninstall()}
      - name: Set up Windows SDK 7.1
        continue-on-error: true
        run: |
          choco install -d windows-sdk-7.1 kb2519277
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Rename the artifact to OS-unique name
        shell: bash
        run: |
          value=`cp build/graal/checksum build/graal/checksum-${{ matrix.os }}`
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: checksum-${{ matrix.os }}.exe
          path: build/graal
