name: Java CI

on: [push]

jobs:
  build-ubuntu-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@latest
    - uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '19.3.0.2.java11'
    - run: java -version
    - name: Build with Gradle
      run: ./gradlew build
    - name: Rename the artifact to OS-unique name
      shell: bash
      run: |
        value=`cp build/graal/checksum build/graal/checksum-${{ matrix.os }}`
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: checksum-${{ matrix.os }}
        path: build/graal

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, windows-latest]

    steps:
      - uses: actions/checkout@latest
      - uses: DeLaGuardo/setup-graalvm@2.0
          with:
          graalvm-version: '19.3.0.2.java11' // GraalVM version, no pattern syntax available atm.
      - run: java -version
      - name: set env variables
        shell: cmd
        run: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      - name: Build with Gradle
        run: ./gradlew build
      - name: Rename the artifact to OS-unique name
        shell: bash
        run: |
          value=`cp build/graal/checksum build/graal/checksum-${{ matrix.os }}`
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: checksum-${{ matrix.os }}.exe
          path: build/graal
