name: Java CI

on: [push]
jobs:
  build-ubuntu-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.0'
        java-version: '11'
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: java -version
    - name: Build with Gradle
      run: ./gradlew build
    - name: Rename the artifact to OS-unique name on Windows
      shell: bash
      if: matrix.os == 'windows-latest'
      run: |
        value=`cp build\graal\checksum build\graal\checksum-${{ matrix.os }}`
    - name: Rename the artifact to OS-unique name on Ubuntu and MacOS
      shell: bash
      if: matrix.os != 'windows-latest'
      run: |
        value=`cp build/graal/checksum build/graal/checksum-${{ matrix.os }}`
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: checksum-${{ matrix.os }}
        path: build/graal
