name: Java CI

on: [push]

jobs:
  build-ubuntu-mac:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: checksum
        path: artifacts/${{ matrix.os }}

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Windows SDK 7.1
        run: |
          choco install windows-sdk-7.1 kb2519277
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: checksum.exe
          path: artifacts/windows-latest
