name: Java CI

on: [push]

jobs:
  build-ubuntu-mac:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Rename the artifact to OS-unique name
      shell: bash
      run: |
        value=`cp build/graal/checksum build/graal/checksum-${{ matrix.os }}`
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: checksum-${{ matrix.os }}
        path: build/graal

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Windows SDK 7.1
        continue-on-error: true
        run: |
          choco install windows-sdk-7.1 kb2519277
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: checksum.exe
          path: build/graal
